### ISSUE TITLE
Can't use my own textures

### ISSUE THREAD

**Issue by ToxyFlog** [CottonMC/LibGui#115]
Identifier TEXTURE = new Identifier("test","textures/gui/background.png");
Background.png is in my resources foulder: assets/test/textures/gui/here it is

Do I need to declare it somewhere?

I'm not 100% sure that problem in that, but when I delete that line everything is back to normal

Error is:
Caused by: net.minecraft.util.InvalidIdentifierException: Non [a-z0-9/._-] character in path of location: test:textures/gui/bacckgroubd.png
	at net.minecraft.util.Identifier.<init>(Identifier.java:36) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at net.minecraft.util.Identifier.<init>(Identifier.java:51) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	at ores.gui.FurnaceController.<clinit>(FurnaceController.java:16) ~[main/:?]
	... 25 more

**Comment by Juuxel** [comment]
Your texture identifier's path contains invalid characters (see the exception message). To fix this, remove them (you might have a whitespace or something there accidentally.

If you need further help with this issue, you can also ask in the Fabric discord's #mod-dev channels.

**Comment by ToxyFlog** [comment]
I know that there is invalid charachters, but how the f**k can I write path without dots and slashes?

**Comment by Juuxel** [comment]
The issue isn't with dots and slashes. You have characters that don't match this regex: `[a-z0-9/._-]` (also in the exception message), meaning something that is not a lowercase ASCII letter, a digit, a slash, a period, an underscore nor a hyphen.

The Fabric discord server is linked somewhere on [Fabric's website](https://fabricmc.net).
