### ISSUE TITLE
crash with dark enchanting

### ISSUE THREAD

**Issue by ITSLOCKED** [CottonMC/LibGui#143]
placing down the enchantment table is fine but once i make the attempt to put in an item it crashes immediately i needed to install not enough crashes because minecraft would stop responding forcing me to task close it when i tried to see again and it crashed this is what popped up

Dark Enchanting 0.4.1-1.17.1 - may have caused crash
LibGui 4.1.7+1.17.1 - may have caused crash
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/18/21, 12:16 AM
Description: Container click

java.lang.IllegalArgumentException: Minimum value must be smaller than the maximum!
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at io.github.cottonmc.cotton.gui.widget.WAbstractSlider.<init>(WAbstractSlider.java:69)
	at io.github.cottonmc.cotton.gui.widget.WLabeledSlider.<init>(WLabeledSlider.java:47)
	at io.github.cottonmc.cotton.gui.widget.WLabeledSlider.<init>(WLabeledSlider.java:36)
	at io.github.frqnny.darkenchanting.client.gui.DarkEnchanterGUI.addNewWidgetToList(DarkEnchanterGUI.java:193)
	at io.github.frqnny.darkenchanting.client.gui.DarkEnchanterGUI.populateList(DarkEnchanterGUI.java:167)
	at io.github.frqnny.darkenchanting.client.gui.DarkEnchanterGUI.fillBox(DarkEnchanterGUI.java:132)
	at io.github.frqnny.darkenchanting.blockentity.inventory.DarkEnchanterInventory.markDirty(DarkEnchanterInventory.java:72)
	at net.minecraft.screen.slot.Slot.markDirty(Slot:66)
	at io.github.cottonmc.cotton.gui.ValidatedSlot.markDirty(ValidatedSlot.java:60)
	at net.minecraft.screen.slot.Slot.setStack(Slot:62)
	at net.minecraft.screen.slot.Slot.method_32755(Slot:146)
	at net.minecraft.screen.ScreenHandler.method_30010(ScreenHandler:405)
	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler:284)
	at io.github.cottonmc.cotton.gui.SyncedGuiDescription.onSlotClick(SyncedGuiDescription.java:178)
	at net.minecraft.client.network.ClientPlayerInteractionManager.clickSlot(ClientPlayerInteractionManager:417)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.onMouseClick(HandledScreen:566)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseReleased(HandledScreen:535)
	at io.github.cottonmc.cotton.gui.client.CottonInventoryScreen.mouseReleased(CottonInventoryScreen.java:197)
	at net.minecraft.client.Mouse.method_1605(Mouse:96)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:96)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:165)
	at net.minecraft.client.util.Window.swapBuffers(Window:310)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.cottonmc.cotton.gui.widget.WAbstractSlider.<init>(WAbstractSlider.java:69)
	at io.github.cottonmc.cotton.gui.widget.WLabeledSlider.<init>(WLabeledSlider.java:47)
	at io.github.cottonmc.cotton.gui.widget.WLabeledSlider.<init>(WLabeledSlider.java:36)
	at io.github.frqnny.darkenchanting.client.gui.DarkEnchanterGUI.addNewWidgetToList(DarkEnchanterGUI.java:193)
	at io.github.frqnny.darkenchanting.client.gui.DarkEnchanterGUI.populateList(DarkEnchanterGUI.java:167)
	at io.github.frqnny.darkenchanting.client.gui.DarkEnchanterGUI.fillBox(DarkEnchanterGUI.java:132)
	at io.github.frqnny.darkenchanting.blockentity.inventory.DarkEnchanterInventory.method_5431(DarkEnchanterInventory.java:72)
	at net.minecraft.class_1735.method_7668(class_1735.java:66)
	at io.github.cottonmc.cotton.gui.ValidatedSlot.method_7668(ValidatedSlot.java:60)
	at net.minecraft.class_1735.method_7673(class_1735.java:62)
	at net.minecraft.class_1735.method_32755(class_1735.java:146)
	at net.minecraft.class_1703.method_30010(class_1703.java:405)

-- Click info --
Details:
	Menu Type: dark-enchanting:dark_enchanter_gui
	Menu Class: io.github.frqnny.darkenchanting.client.gui.DarkEnchanterGUI
	Slot Count: 37
	Slot: 0
	Button: 0
	Type: PICKUP
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:521)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:169)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:493)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:96)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:165)
	at net.minecraft.client.util.Window.swapBuffers(Window:310)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected screen --
Details:
	Screen name: io.github.cottonmc.cotton.gui.client.CottonInventoryScreen
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:521)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.world.World.addDetailsToCrashReport(World:845)
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld:370)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2399)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected level --
Details:
	All players: 1 total; [class_746['IXlX'/70, l='ClientLevel', x=240.96, y=70.00, z=-3193.40]]
	Chunk stats: 4096, 961
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 24770 game time, 30283 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Luminous1.2.zip, §fAnimated+§cR§aG§9B+§fInv.+GUI+1.16.5.zip, charmonium/journeyman, Alittle+Axolotl+[5.0].zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 976484288 bytes (931 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9676
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18363.25
	Virtual memory used (MB): 11642.59
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 389.04
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 2.2.0+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementplaques: Advancement Plaques 1.4.2
		alaskanativecraft: Alaska Native Craft 1.3.1
		alloy_forgery: Alloy Forgery 2.0.6
		ambientenvironment: Ambient Environment 6.0.22
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.5.32
		artifacts: Artifacts 5.0.2+fabric
		attackspeedplus: Attack Speed Plus 1.17.1-2.0
		attributefix: Attribute Fix {FABRIC} 1.0.3
		awesomedungeon: Awesome Dungeon 1.1.2
		barrenisles: Barren Isles 1.0.7
		battletowers: Battle Towers 3.4.1-1.17.1
		bettereating: Better Eating 0.3.0
		biomepicker: Biome Picker 1.1.1
		blue_endless_jankson: jankson 1.2.1
		campanion: Campanion 2.0.1
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		collective-fabric: Collective (Fabric) 1.62
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_github_reviversmc_modget-lib: modget-lib 2.0.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cosmetic-armor: Cosmetic Armor 1.1.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		custom-crosshair-mod: Custom Crosshair Mod 1.3.6-fabric
		customportalapi: Custom Portal Api 0.0.1-beta45-1.17
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		dark-loading-screen: Dark Loading Screen 1.6.11
		dbm: Dispenser Bazooka Mod 1.0.6
		decorative: Decorative 4.1.1
		desolation: Desolation 1.1.5
		diggusmaximus: Diggus Maximus 1.5.1-1.17
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		disenchanter: Disenchanter 0.1.2
		dragonloot: DragonLoot 1.0.9
		durability101: Durability101 0.0.4
		earthtojavamobs: Earth2Java 1.7.3+1.17
		eldritch_mobs: Eldritch Mobs 1.9.6
		elementalswords: Elemental Swords 1.17.1-1.0.0-[FABRIC]
		emerald_tools: Emerald Tools 1.2.27
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enchantmentnumeralfix: Enchantment Numeral Fix 1.0.0
		enhancedblockentities: Enhanced Block Entities 0.5+1.17
		enhancedcelestials: Enhanced Celestials 2.0.5
		expandability: ExpandAbility 4.0.2
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.1
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.2
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.1
		expandedstorage: Expanded Storage 7.2.7
		extended_armor_bars: Extended Armor Bars 1.1.0
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricenchantments: Fabric Enchantments 0.4.2
		fabricloader: Fabric Loader 0.11.7
		fallingleaves: Falling Leaves 1.7.4+1.17.1
		fatxporbs: Fat Experience Orbs 1.0.1
		fiber: fiber 0.23.0-2
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.9
		fourinchknife-trueinfinity: True Infinity 1.2.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.11
		gobber2: Gobber2 2.4.53
		goldensteak: Goldensteak 1.0.5
		guardiansgalore: GuardiansGalore 1.17.1-2.1
		health_levels: Health Levels 1.0.1
		healthoverlay: Health Overlay 4.0.2
		highlighter: Highlighter 1.1.1
		humans: Humans 0.2.0-beta.1+1.17
		hydrogen: Hydrogen 0.3
		iceberg: Iceberg 1.0.23
		illuminations: Illuminations 1.10
		impaled: Impaled 1.0.1
		improved-stations: Improved Stations 2.0.7
		indium: Indium 1.0.0+mc1.17.1
		inventoryhud: Inventory HUD + 3.4.0
		iris: Iris 1.1.2+build.9
		ironfurnaces: Iron Furnaces 1.17.1-2.6.1-fabric
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.9.1
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		legendarytooltips: Legendary Tooltips 1.1.1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.7+1.17.1
		libninepatch: LibNinePatch 1.1.0
		lightsaber: SurvivalPlus Lightsabers 0.1.6
		lithium: Lithium 0.7.4
		lootcrates: Modular Loot Crates 2.2.0
		lovely_snails: Lovely Snails 1.0.3+1.17
		lucky: Lucky Block 1.17.1-1
		malusphaethusa: Malus Phaethusa 1.0.1
		mcda: MC Dungeons Armors 1.7.15
		mcdw: MC Dungeons Weapons 3.5.5
		mcsa: MC Story Mode Armor 2.3.2-1.17
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.17.1
		mining_dims: Mining Dimensions 1.1.13
		mobz: MobZ 3.2.0
		modget: Modget 0.2.3
		modmenu: Mod Menu 2.0.14
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		morevillagesmod: More Villages Mod 1.0.0
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mythicmetals: Mythic Metals 0.10.1
		naturallychargedcreepers-fabric: Naturally Charged Creepers (Fabric) 1.7
		neopi: NEOPI 1.1.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.4
		noenchantcap: NoEnchantCap 4.1.0
		notenoughcrashes: Not Enough Crashes 3.7.2+1.17.1
		noweakattack: No Weak Attack 1.1.2
		npcvariety: NPC Variety 2.2.0
		omega-config: OmegaConfig 1.0.8
		opchanter: OPChanter 1.17.1-1.0.0-fabric
		org_apache_commons_commons-text: commons-text 1.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		owo: oωo 0.3.1
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17.1-56-FABRIC
		playerabilitylib: Pal 1.3.0
		polymorph: Polymorph 0.0.14-1.17.1
		portalswords: Portal Swords 1.2-1.17.x
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		puddles: Puddles 1.2.0
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		rare-ice: Rare Ice 0.3.0
		ratsmischief: Rat's Mischief 1.3.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.0.287-alpha
		rpgdifficulty: Rpg Difficulty 1.0.7
		rpgstats: RPGStats 4.2.2+1.17.1
		seasons: Fabric Seasons 1.3.1-BETA+1.17
		server_translations_api: Server Translations API 1.4.5+1.17
		skinlayers: 3d Skin Layers 1.2.1
		snowpig: Snow Pig 1.2.0
		sodium: Sodium 0.3.2+IRIS2-build.9
		spellbound: Spellbound 1.6.0
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stepup: StepUp 1.17.1-fabric0.36.1-1.1
		stonevaults: Stonevaults 1.1.0
		structure-helpers: Structure Helpers 3.2.0
		survivalplus: SurvivalPlus 0.1.5
		team_reborn_energy: Energy 0.1.1
		toolstats: Tool Stats 2.0.1
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		transparent-armor: Transparent Armor 1.0
		trinkets: Trinkets 3.0.4
		trumpet-skeleton: Trumpet Skeleton 1.1.4
		untitledduckmod: Untitled Duck Mod 0.3.0
		valley: ValleyCraft 1.3.2
		vanilla_degus: Vanilla Degus 1.2.3
		villagernames: Villager Names 2.0.1
		whm: Wither Hoe Mod 1.3.4
		wthit: wthit 3.9.3
		xaerominimap: Xaero's Minimap 21.21.0
		xaeroworldmap: Xaero's World Map 1.18.1
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.0
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 496.76, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Luminous1.2.zip (incompatible), file/§fAnimated+§cR§aG§9B+§fInv.+GUI+1.16.5.zip (incompatible), charmonium/journeyman, file/Alittle+Axolotl+[5.0].zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	Player Count: 1 / 8; [class_3222['IXlX'/70, l='ServerLevel[New World]', x=240.96, y=70.00, z=-3193.40]]
	Data Packs: vanilla, Fabric Mods
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader), Dark Enchanting (dark-enchanting), LibGui (libgui)

**Comment by Juuxel** [comment]
This is a dark enchanting bug, please report it to them.
