### ISSUE TITLE
[Bug] ConcurrentModificationException in CottonHud

### ISSUE THREAD

**Issue by alex3236** [CottonMC/LibGui#164]
**Describe the bug**
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at io.github.cottonmc.cotton.gui.client.CottonHud.lambda$static$0(CottonHud.java:30)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$zgc000$render(class_329.java:1529)
	at net.minecraft.class_329.method_1753(class_329.java:415)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**To Reproduce**
(Maybe) Use `CottonHud.remove` to remove a HUD before the `HudRenderCallback` is finished

**Expected behavior** *Optional*

**Screenshots** *Optional*

**Version of the (please complete the following information):**
 - LibGui 5.4.0 on 1.18.2

**Additional context** *Optional*

**Comment by alex3236** [comment]
https://github.com/CottonMC/LibGui/blob/9ca8ba7f9d1baac7dd8e7a66fb6a03675df3af1c/src/main/java/io/github/cottonmc/cotton/gui/client/CottonHud.java#L23

I think change `new HashMap<>()` to `Collections.synchronizedMap(new HashMap<>())` or `new ConcurrentHashMap<>();` should work?
