### ISSUE TITLE
Out of index when typing after tabbing into a blank WTextField

### ISSUE THREAD

**Issue by RealAso** [CottonMC/LibGui#196]
The game crashes right after tabbing into a blank text field and typing a character, but won't crash if clicking on the field and typing

```
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4608)
	at java.base/java.lang.String.substring(String.java:2720)
	at io.github.cottonmc.cotton.gui.widget.WTextField.insertText(WTextField.java:379)
	at io.github.cottonmc.cotton.gui.widget.WTextField.onCharTyped(WTextField.java:366)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.charTyped(CottonClientScreen.java:233)
	at net.minecraft.client.Keyboard.method_1458(Keyboard.java:439)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:564)
	at net.minecraft.client.Keyboard.onChar(Keyboard.java:439)
	at net.minecraft.client.Keyboard.method_22677(Keyboard.java:452)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:101)
	at net.minecraft.client.Keyboard.method_22675(Keyboard.java:452)
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:164)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:173)
	at net.minecraft.client.util.Window.swapBuffers(Window.java:319)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1141)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:774)
	at net.minecraft.client.main.Main.main(Main.java:210)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by RealAso** [comment]
I fixed this by overriding the onFocusGained() method in WTextField ensuring that the text cursor is never -1:
```
@Override
                public void onFocusGained() {
                    if (this.getCursor() == -1) {
                        this.setCursorPos(0);
                    }
                }
```

**Comment by Juuxel** [comment]
It's still an issue that needs to be fixed in LibGui itself, so I'll keep this issue open until then.
