### ISSUE TITLE
[BUG] Cant use resource packs in 1.19.4

### ISSUE THREAD

**Issue by MarkinhosMLP** [CottonMC/LibGui#197]
i have no idea of which mod is causing this but it says the error is in the lib gui jar (which is included in my mod list somehow)
![image](https://github.com/CottonMC/LibGui/assets/47507632/80ba5bff-b8e6-4dae-80fa-2423ff02567f)

[14:45:30] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1174) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at net.minecraft.class_2960.method_12830(class_2960.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:51) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.rewriteAsId(FabricShaderProgram.java:42) ~[fabric-rendering-v1-2.1.2+504944c8f4-d3f123cd32cf48f7.jar:?]
	at net.minecraft.class_5944.modify$ben000$fabric-rendering-v1$modifyProgramId(class_5944.java:654) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.localvar$cio000$optifabric$modifyProgramID(class_5944.java:1634) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:114) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:108) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.<init>(FabricShaderProgram.java:28) ~[fabric-rendering-v1-2.1.2+504944c8f4-d3f123cd32cf48f7.jar:?]
	at net.minecraft.class_757.md2a3544$fabric-rendering-v1$lambda$registerShaders$0$2(class_757.java:4627) ~[client-intermediary.jar:?]
	**at io.github.cottonmc.cotton.gui.impl.client.LibGuiShaders.lambda$register$1(LibGuiShaders.java:18) ~[libgui-7.0.0-beta.2+1.19.4-5d9ab1b6fd19d93b.jar:?]**
	at net.fabricmc.fabric.api.client.rendering.v1.CoreShaderRegistrationCallback.lambda$static$0(CoreShaderRegistrationCallback.java:44) ~[fabric-rendering-v1-2.1.2+504944c8f4-d3f123cd32cf48f7.jar:?]
	at net.minecraft.class_757.handler$bel000$fabric-rendering-v1$registerShaders(class_757.java:4630) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:536) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:460) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:432) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more

**Comment by Juuxel** [comment]
LibGui is only using Fabric API's methods here, so we shouldn't be the cause of the crash. I can see Optifabric further in the crash stacktrace, so you could try asking them for help.

(Also, LibGui is most likely in your mod list as a mod that another mod bundles inside itself.)
