### ISSUE TITLE
[BUG] Opening config with ModMenu causes crashes

### ISSUE THREAD

**Issue by MarkinhosMLP** [CottonMC/LibGui#198]
![image](https://github.com/CottonMC/LibGui/assets/47507632/f7e519c8-ae7a-4040-b7fd-1c1e67d151dc)
![image](https://github.com/CottonMC/LibGui/assets/47507632/dde1530b-1c5b-4aa4-bd16-1911f7254471)

java.lang.NullPointerException: Shader libgui:tiled_rectangle not initialised!
	at io.github.cottonmc.cotton.gui.impl.client.LibGuiShaders.assertPresent(LibGuiShaders.java:24)
	at io.github.cottonmc.cotton.gui.impl.client.LibGuiShaders.getTiledRectangle(LibGuiShaders.java:31)
	at com.mojang.blaze3d.systems.RenderSystem.setShader(RenderSystem.java:1001)
	at io.github.cottonmc.cotton.gui.impl.client.NinePatchTextureRendererImpl.drawTiled(NinePatchTextureRendererImpl.java:32)
	at io.github.cottonmc.cotton.gui.impl.client.NinePatchTextureRendererImpl.drawTiled(NinePatchTextureRendererImpl.java:22)
	at juuxel.libninepatch.ContextualTextureRenderer.drawTiled(ContextualTextureRenderer.java:128)
	at juuxel.libninepatch.NinePatch.drawTiling(NinePatch.java:94)
	at juuxel.libninepatch.NinePatch.draw(NinePatch.java:54)
	at io.github.cottonmc.cotton.gui.client.NinePatchBackgroundPainter.paintBackground(NinePatchBackgroundPainter.java:102)
	at io.github.cottonmc.cotton.gui.client.BackgroundPainter.lambda$createLightDarkVariants$4(BackgroundPainter.java:155)
	at io.github.cottonmc.cotton.gui.widget.WPanel.paint(WPanel.java:142)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.paint(CottonClientScreen.java:135)
	at io.github.cottonmc.cotton.gui.client.CottonClientScreen.method_25394(CottonClientScreen.java:149)
	at net.minecraft.class_437.method_47413(class_437.java:121)
	at net.minecraft.class_757.method_3192(class_757.java:1388)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Juuxel** [comment]
Can you share your mod list?

**Comment by Juuxel** [comment]
Closing this since there's no further info that can help me solve the issue.
