### ISSUE TITLE
Entry point "client" cannot be executed

### ISSUE THREAD

**Issue by fhrk-78** [CottonMC/LibGui#237]
**(Translated from Japanese to English by a translation application, so there may be mistakes.)**

Please help. I am developing a GUI (latest version) using LibGUI, and it works fine in runClient, but in actual execution it says "class `io/github/cottonmc/cotton/gui/GuiDescription` not found, no declaration" and crashes. and it crashes.

### Additional Information

| Name | BuildVersion | TestEnvVersion |
| - | - | - |
| Minecraft | 1.20.4 | 1.20.4 |
| Fabric Loader | 0.15.7 | 0.15.7 |
| Fabric API | 0.96.3+1.20.4 | 0.96.3+1.20.4 |

- Java : 17
- Gradle : 8.6
- LibGUI : 9.2.2+1.20.2

The following is a part of build.gradle

```gradle
repositories {
	maven {
		name = "CottonMC"
		url = "https://server.bbkr.space/artifactory/libs-release"
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	modImplementation "io.github.cottonmc:LibGui:9.2.2+1.20.2"
}
```

Crash log.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by '~~~~~'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/cotton/gui/GuiDescription
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.cotton.gui.GuiDescription
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 12 more
```

I am familiar with C++, etc., but I have no knowledge of Java, so I would like to ask you about it.

**Comment by fhrk-78** [comment]
勝手に閉じてごめんなさい、私の勘違いだったようです
