### ISSUE TITLE
Scroll panels cause the game to crash

### ISSUE THREAD

**Issue by commandblockguy** [CottonMC/LibGui#71]
**Describe the bug**
Using a WScrollPanel widget causes the game to crash.

**To Reproduce**
1. Create a scroll panel and add it to a panel:
```
WLabel test = new WLabel(new LiteralText("test"));
WScrollPanel scrollPanel = new WScrollPanel(test);
root.add(scrollPanel, 0, 0);
```
2. Display the root panel
3. The game crashes

**Versions:**
 - Mod: 1.10.0
 - Fabric API: 0.14.0+build.317-1.15
 - Minecraft: 1.15.2

**Additional context**
The relevant sections of the crash log:
```
...
java.lang.NoSuchMethodError: io.github.cottonmc.cotton.gui.widget.WScrollBar.setMaxValue(I)V
	at io.github.cottonmc.cotton.gui.widget.WScrollPanel.layout(WScrollPanel.java:98)
	at io.github.cottonmc.cotton.gui.widget.WPanel.layout(WPanel.java:74)
	at io.github.cottonmc.cotton.gui.widget.WPanel.validate(WPanel.java:174)
...
-- Head --
Thread: Render thread
Stacktrace:
	at io.github.cottonmc.cotton.gui.widget.WScrollPanel.layout(WScrollPanel.java:98)
	at io.github.cottonmc.cotton.gui.widget.WPanel.layout(WPanel.java:74)
	at io.github.cottonmc.cotton.gui.widget.WPanel.validate(WPanel.java:174)
...
```

**Comment by Juuxel** [comment]
LibGui versions for outdated releases are not supported.
