### ISSUE TITLE
Rendering a WBar on HUD causes NullPointerException

### ISSUE THREAD

**Issue by cocona20xx** [CottonMC/LibGui#92]
**Describe the bug**
When a WBar is rendered on the HUD, it causes a NullPointerException.
**To Reproduce**
1. Create a valid WBar with the `(Identifier, Identifier, int, int)` constructor, with valid `Identifier`s for the bar visuals.
2. Add the WBar to the HUD via `CottonHud.INSTANCE.add()` in the Client entrypoint.
3. When launching into a world, game will now throw a NullPointerException!

**Expected behavior** *Optional*
The bar renders correctly on the HUD.

**Screenshots** *Optional*
Instead of a screenshot, have a stacktrace:
```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11/8/20 4:22 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at io.github.cottonmc.cotton.gui.widget.WBar.paint(WBar.java:121)
	at io.github.cottonmc.cotton.gui.client.CottonHud.onHudRender(CottonHud.java:128)
	at net.minecraft.client.gui.hud.InGameHud.handler$zep000$render(InGameHud.java:1279)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:345)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:470)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:984)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:601)
	at net.minecraft.client.main.Main.main(Main.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.cottonmc.cotton.gui.widget.WBar.paint(WBar.java:121)
	at io.github.cottonmc.cotton.gui.client.CottonHud.onHudRender(CottonHud.java:128)
	at net.minecraft.client.gui.hud.InGameHud.handler$zep000$render(InGameHud.java:1279)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:345)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Player581'/130, l='ClientLevel', x=109.50, y=65.00, z=225.50]]
	Chunk stats: Client Chunk Cache: 841, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,65,224), Chunk: (at 0,4,0 in 7,14; contains blocks 112,0,224 to 127,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12452 game time, 12452 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:454)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2116)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:622)
	at net.minecraft.client.main.Main.main(Main.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

```
and the error at runtime:
```
[04:22:52] [main/FATAL] (Minecraft) Unreported exception thrown!
 java.lang.NullPointerException: null
	at io.github.cottonmc.cotton.gui.widget.WBar.paint(WBar.java:121) ~[LibGui-3.2.1+1.16.3@net.fabricmc.yarn.1_16_3.1.16.3+build.47-v2.jar:?]
	at io.github.cottonmc.cotton.gui.client.CottonHud.onHudRender(CottonHud.java:128) ~[LibGui-3.2.1+1.16.3@net.fabricmc.yarn.1_16_3.1.16.3+build.47-v2.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$zep000$render(InGameHud.java:1279) ~[minecraft-1.16.3-mapped-net.fabricmc.yarn-1.16.3+build.47-v2.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:345) ~[minecraft-1.16.3-mapped-net.fabricmc.yarn-1.16.3+build.47-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:470) ~[minecraft-1.16.3-mapped-net.fabricmc.yarn-1.16.3+build.47-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:984) ~[minecraft-1.16.3-mapped-net.fabricmc.yarn-1.16.3+build.47-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:601) [minecraft-1.16.3-mapped-net.fabricmc.yarn-1.16.3+build.47-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) [minecraft-1.16.3-mapped-net.fabricmc.yarn-1.16.3+build.47-v2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_3.1.16.3+build.47-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_3.1.16.3+build.47-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214@net.fabricmc.yarn.1_16_3.1.16.3+build.47-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Version of the (please complete the following information):**
 - LibGui version: 3.2.1+1.16.3
 - Fabric API version: 0.25.0+build.415-1.16
 - Minecraft version: 1.16.3

**Comment by Juuxel** [comment]
If you have a bar in the HUD, you need to set its `PropertyDelegate` manually with `WBar.setProperties`. So your code would be something like this:

```java
PropertyDelegate properties = /* some PropertyDelegate implementation */;
WBar bar = new WBar(...).setProperties(properties);
```

**Comment by cocona20xx** [comment]
Ok, how many properties is the bar supposed to have? I presume 2, for the current and max values?

**Comment by cocona20xx** [comment]
Figured it out myself, for a `PropertyDelegate` holding 2 values, set the WBar's `field` and `maxField` properties to `0` and `1`
